events {}

http {
    upstream frontend_servers {
        server ui1:5173;
        server ui2:5173;
        server ui3:5173;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://frontend_servers;
            proxy_set_header Accept-Encoding "";
        }
    }
}