upstream frontend_servers {
    server ui1:3000;
    server ui2:3000;
    server ui3:3000;
}

server {
    listen 80;

    # Frontend
    location / {
        proxy_pass http://frontend_servers;
        proxy_set_header Host $host;
    }

    # Backend API (optional if you proxy /api)
    location /api/ {
        proxy_pass http://voting_backend:3000;  # your backend container name
        proxy_set_header Host $host;
    }

    # WebSocket for backend
    location /socket.io/ {
        proxy_pass http://voting_backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}